export type { 
  HardwareTopology,
  NodeSpec,
  DeviceSpec,
  MemorySpec,
  ComputeSpec,
  InterconnectSpec,
  ModelProfile,
  ModelProfileProvenance,
  ModelComponentProfile,
  MediaInputProfile,
  MediaModality,
  ModelComponentPhase,
  DiffusionProfile,
  ModelArchitecture,
  MoEProfile,
  ExpertDistribution,
  LayerProfile,
  Quantization,
  QuantType,
  PipelineConfig,
  ParallelismConfig,
  MemoryPolicyConfig,
  StaticAnalysisResult,
  DeviceMemoryBreakdown,
  HostMemoryBreakdown,
  ThroughputEstimate,
  SimEvent,
  SimTrace,
  SimSummary,
} from "./types.js";

export { GPU_PRESETS, buildTopology, listPresets } from "./presets.js";
export { compareIds } from "./ordering.js";
export {
  MULTI_MODEL_TRACE_REVISION,
  MultiModelProtocolError,
  replayMultiModelTrace,
  simulateMultiModelWorkload,
  tenantFootprintBytes,
  validateMultiModelConfig,
  type MultiModelBatchDurationEstimator,
  type MultiModelBatchWork,
  type MultiModelConfig,
  type MultiModelMetrics,
  type MultiModelRequestResult,
  type MultiModelRequestSpec,
  type MultiModelResult,
  type MultiModelTenantMetrics,
  type MultiModelTenantSpec,
  type MultiModelTraceEvent,
} from "./multi-model.js";
export {
  derivedMemoryBandwidth,
  type MemoryBusSpec,
} from "./memory-bus.js";
export {
  expertRoutingWeights,
  planExpertResidency,
  topExpertMass,
  type ExpertResidencyPlan,
} from "./expert-residency.js";
export {
  expertCacheFromModel,
  expertCacheTierDomains,
  type ExpertCacheTierDomains,
  type ModelBoundExpertCache,
} from "./model-expert-cache.js";
export {
  MODEL_PRESETS,
  MODEL_SPECS,
  buildModelProfile,
  derivedTotalParams,
  listModelPresets,
  type AttentionGeometry,
  type GqaAttention,
  type LinearAttention,
  type MlaAttention,
  type ModelSpec,
} from "./models.js";
export { analyzeStatic } from "./static-analysis.js";
export {
  searchStaticConfigurations,
  type StaticSearchCandidate,
  type StaticSearchConstraints,
  type StaticSearchObjective,
  type StaticSearchProgress,
  type StaticSearchRequest,
  type StaticSearchResult,
  type StaticSearchSpace,
  type StaticSearchTopology,
} from "./static-search.js";
export {
  SIMULATION_RESULT_ARTIFACT_KIND,
  SIMULATION_RESULT_ARTIFACT_REVISION,
  SimulationResultArtifactError,
  canonicalJsonFingerprint,
  canonicalJsonStringify,
  createSimulationResultArtifact,
  parseSimulationResultArtifact,
  serializeSimulationResultArtifact,
  type SimulationResultArtifact,
} from "./result-artifact.js";
export {
  FROZEN_PLAN_ARTIFACT_KIND,
  FROZEN_PLAN_ARTIFACT_REVISION,
  FrozenPlanArtifactError,
  createFrozenPlanArtifact,
  parseFrozenPlanArtifact,
  serializeFrozenPlanArtifact,
  type FrozenPlanArtifact,
} from "./frozen-plan-artifact.js";
export {
  ScenarioParseError,
  parseSimulationScenario,
} from "./scenario-parser.js";
export {
  InferenceMetadataError,
  parseInferenceMetadata,
  type InferenceMetadataSpeculativeEvidence,
  type InferenceMetadataSummary,
  type InferencePipelineComponent,
  type InferencePipelineEdge,
  type InferencePipelineStage,
} from "./inference-metadata.js";
export {
  ONNX_MODEL_MANIFEST_KIND,
  ONNX_MODEL_MANIFEST_REVISION,
  OnnxModelManifestError,
  createOnnxModelManifest,
  parseOnnxModelManifest,
  serializeOnnxModelManifest,
  type OnnxArchitectureEvidence,
  type OnnxExternalDataFileManifest,
  type OnnxInitializerManifest,
  type OnnxModelManifest,
  type OnnxModelManifestUnsigned,
  type OnnxOperatorCount,
  type OnnxTensorStorage,
} from "./onnx-manifest.js";
export {
  resolveOnnxModelProfile,
  type OnnxModelProfileOptions,
} from "./onnx-model-profile.js";
export {
  DiscreteEventSimulator,
  SimulationError,
  type ScheduledEvent,
  type SimulationEventHandler,
  type SimulationRunOptions,
  type SimulationRunResult,
} from "./event-loop.js";
export {
  DEFAULT_SERVING_BATCH_DURATION,
  SERVING_TRACE_CONTRACT_REVISION,
  ServingProtocolError,
  replayServingTrace,
  simulateServingWorkload,
  type ServingBatchDurationEstimator,
  type ServingBatchWork,
  type ServingDecodeSlice,
  type ServingMetrics,
  type ServingPrefillSlice,
  type ServingReplayResult,
  type ServingRequestResult,
  type ServingRequestSpec,
  type ServingSchedulerConfig,
  type ServingSimulationResult,
  type ServingSpeculativeAcceptanceModel,
  type ServingSpeculativeConfig,
  type ServingTokenEmission,
  type ServingTraceEvent,
} from "./serving.js";
export {
  SERVING_EXPERT_CACHE_CONTRACT_REVISION,
  compareTopologyServingWorkloads,
  expertCacheConfigForTopology,
  simulateTopologyServingWorkload,
  topologyProfileFromServingBatch,
  type TopologyServingBatchResult,
  type TopologyServingComparisonResult,
  type TopologyServingComparisonRun,
  type TopologyServingExpertCacheConfig,
  type TopologyServingExpertCacheResult,
  type TopologyServingMetrics,
  type TopologyServingPhysicalResult,
  type TopologyServingResult,
} from "./serving-topology.js";
export {
  HostGovernorSimulator,
  PressureProtocolError,
} from "./pressure.js";
export {
  PressureReplayError,
  replayPressureTrace,
} from "./pressure-replay.js";
export {
  PROTOCOL_CONTRACT_REVISION,
  type HostAllocationSnapshot,
  type HostAllocationState,
  type HostGovernorConfig,
  type HostGovernorSnapshot,
  type PressureReplayResult,
  type PressureTicketSnapshot,
  type PressureTicketState,
  type PressureTraceEvent,
  type PressureTracePayload,
} from "./pressure-types.js";
export {
  SpeculativeProtocolError,
  SpeculativeTransactionSimulator,
  type RollbackProtection,
  type SpeculativeIterationInput,
  type SpeculativeIterationResult,
  type SpeculativeStateGroupConfig,
  type SpeculativeStateGroupSnapshot,
  type SpeculativeStateLifetime,
  type SpeculativeStateOwner,
  type SpeculativeStateRole,
} from "./speculative.js";
export {
  SPECULATIVE_FAMILY_CONTRACT_REVISION,
  SpeculativeEligibilityError,
  buildSpeculativeStateGroups,
  defaultSpeculativeEligibility,
  speculativeFamilyContract,
  validateSpeculativeEligibility,
  validateSpeculativeStateGroups,
  type SpeculativeEligibility,
  type SpeculativeFamilyContract,
  type SpeculativeFamilySupport,
  type SpeculativeProposerExecution,
  type SpeculativeProposalPrefix,
} from "./speculative-family.js";
export {
  SPECULATIVE_ITERATION_CONTRACT_REVISION,
  SpeculativeIterationError,
  decideSpeculativeIteration,
  planSpeculativeProposal,
  type SpeculativeIterationDecision,
  type SpeculativeProposalShape,
} from "./speculative-iteration.js";
export {
  SpeculativeAcceptanceCursor,
  SpeculativeAcceptanceError,
  validateAcceptanceCoverage,
  type SpeculativeAcceptanceModel,
} from "./speculative-acceptance.js";
export {
  SpeculativeWorkloadError,
  simulateSpeculativeWorkload,
  type SpeculativeProposerFamily,
  type SpeculativePagedKvResult,
  type SpeculativeProposalWidthModel,
  type SpeculativeWorkloadConfig,
  type SpeculativeWorkloadIteration,
  type SpeculativeWorkloadMetrics,
  type SpeculativeWorkloadResult,
} from "./speculative-workload.js";
export {
  SPECULATIVE_TOKEN_TRACE_REVISION,
  SpeculativeTokenTraceError,
  parseSpeculativeTokenTrace,
  simulateSpeculativeTokenTrace,
  validateSpeculativeTokenTrace,
  type SpeculativeTokenDifferential,
  type SpeculativeTokenMismatch,
  type SpeculativeTokenTrace,
  type SpeculativeTokenTraceIteration,
  type SpeculativeTokenTraceIterationResult,
  type SpeculativeTokenTraceProvenance,
  type SpeculativeTokenTraceResult,
} from "./speculative-token-trace.js";
export {
  SPECULATIVE_RUNTIME_CAPTURE_REVISION,
  SpeculativeRuntimeCaptureError,
  bindParsedRuntimeCaptures,
  bindSpeculativeRuntimeCaptures,
  parseRuntimeTokenCapture,
  validateRuntimeTokenCapture,
  type BoundSpeculativeRuntimeCapture,
  type RuntimeTokenCapture,
  type SpeculativeRuntimeCapture,
  type SpeculativeRuntimeCaptureIteration,
  type SpeculativeRuntimeCaptureProvenance,
  type SpeculativeRuntimeCaptureTerminal,
  type TargetOnlyRuntimeCapture,
} from "./speculative-runtime-capture.js";
export {
  PAGED_KV_CONTRACT_REVISION,
  PagedKvCacheSimulator,
  PagedKvProtocolError,
  PagedKvReplayError,
  replayPagedKvTrace,
  type PagedKvCheckpoint,
  type PagedKvConfig,
  type PagedKvPageSnapshot,
  type PagedKvReplayResult,
  type PagedKvSnapshot,
  type PagedKvTraceEvent,
} from "./paged-kv.js";
export {
  EXPERT_CACHE_CONTRACT_REVISION,
  ExpertCacheProtocolError,
  ExpertCacheReplayError,
  ExpertCacheSimulator,
  replayExpertCacheTrace,
  simulateExpertCacheWorkload,
  type AdaptiveExpertPrefetchPolicy,
  type ExpertCacheConfig,
  type ExpertCacheMetrics,
  type ExpertCachePartitionSnapshot,
  type ExpertCacheReplayResult,
  type ExpertCacheSnapshot,
  type ExpertCacheTier,
  type ExpertCacheTierPartition,
  type ExpertCacheTraceEvent,
  type ExpertCacheWorkloadConfig,
  type ExpertCacheWorkloadResult,
  type ExpertLoadKind,
  type ExpertLoadTarget,
  type ExpertPendingLoadSnapshot,
  type ExpertPendingRoute,
  type ExpertRouteRequest,
  type ExpertRouteResult,
  type ExpertSpec,
} from "./expert-cache.js";
export {
  SCENARIO_SCHEMA_VERSION,
  type AllocationClass,
  type AllocationReservation,
  type CalibrationCoefficient,
  type CalibrationSet,
  type CommunicatorGroupSpec,
  type CommunicatorRankSpec,
  type ComputeCapability,
  type ConfidenceClass,
  type CustomComputePeakSpec,
  type EvidenceProvenance,
  type GovernorOwner,
  type MemoryDomainKind,
  type MemoryDomainSpec,
  type NetworkResourceSpec,
  type NetworkTransportMode,
  type PartitionPlacement,
  type ScenarioExecutionPolicy,
  type ScenarioValidationIssue,
  type ScenarioValidationResult,
  type AllocationPurpose,
  type ScenarioMemoryLedgerEntry,
  type ScenarioMemoryLedgerOptions,
  type ScenarioWorkloadSpec,
  type SimDeviceKind,
  type SimDeviceSpec,
  type SimLinkSpec,
  type SimulationScenario,
  type TransferRequirement,
  type TransferRoute,
} from "./scenario-types.js";
export {
  HARDWARE_COMPUTE_PROFILES,
  HARDWARE_COMPUTE_REGISTRY_REVISION,
  denseHardwareComputePeak,
  hardwareComputeDtypes,
  hardwareComputeProfile,
  type HardwareComputeDtype,
  type HardwareComputePeak,
  type HardwareComputeProfile,
  type HardwareComputeSource,
} from "./hardware-compute-profiles.js";
export {
  ScenarioValidationError,
  assertValidScenario,
  calculateLinkDurationNs,
  calculateScenarioMemoryLedger,
  domainSupportsClass,
  findTransferPath,
  findTransferRoute,
  validateScenario,
} from "./scenario.js";
export {
  ALL_SCENARIO_PRESET_NAMES,
  COMPUTER_PRESET_NAMES,
  SCENARIO_PRESET_NAMES,
  buildMultiNodeLanScenario,
  buildMultiGpuRingScenario,
  buildScenarioPreset,
  configureSmallLanNetwork,
  type MultiNodeLanNodeCount,
  type MultiNodeLanOptions,
  type ScenarioPresetName,
} from "./scenario-presets.js";
export {
  PLAN_CONTRACT_REVISION,
  type CollectiveAlgorithm,
  type FrozenPlan,
  type FrozenPlanExecutionResult,
  type PlanExecutionOptions,
  type PlanExecutionTrace,
  type PlanFault,
  type PlanFaultCampaignCase,
  type PlanFaultCampaignResult,
  type PlanOperation,
  type PlanReplayResult,
  type PlanResourceReservation,
  type PlanStep,
  type PlanTerminalEvent,
  type PlanTerminalStatus,
  type PlanTraceEvent,
  type PlanValidationIssue,
  type PlanValidationResult,
  type RankCompletion,
  type RankTerminalState,
} from "./plan-types.js";
export {
  CollectiveSubmitSequencer,
  FrozenPlanExecutionError,
  FrozenPlanValidationError,
  PlanReplayError,
  assertValidFrozenPlan,
  executeFrozenPlan,
  replayPlanTrace,
  runPlanFaultCampaign,
  validateFrozenPlan,
} from "./frozen-plan.js";
export {
  CONCURRENT_PLAN_TRACE_REVISION,
  StreamingConcurrentPlanRuntime,
  executeConcurrentFrozenPlans,
  executeConcurrentNodeFailure,
  replayConcurrentPlanTrace,
  runSeededConcurrentNodeFailureCampaign,
  runSeededConcurrentPlanCampaign,
  type ConcurrentPlanAdmission,
  type ConcurrentPlanCampaignOptions,
  type ConcurrentPlanCampaignResult,
  type ConcurrentNodeFailure,
  type ConcurrentNodeFailureCampaignResult,
  type ConcurrentPlanExecutionResult,
  type ConcurrentPlanExecutionTrace,
  type ConcurrentPlanOperationEvent,
  type ConcurrentPlanReplayResult,
  type ConcurrentPlanReplayOptions,
  type ConcurrentPlanRequest,
  type StreamingPlanStepCompletion,
} from "./concurrent-plan.js";
export {
  NODE_RECOVERY_CONTRACT_REVISION,
  replayNodeFailoverCampaign,
  runNodeFailoverCampaign,
  type NodeFailoverHandoff,
  type NodeFailoverReplayResult,
  type NodeFailoverRequest,
  type NodeFailoverResult,
} from "./node-recovery.js";
export {
  CALIBRATION_DATASET_REVISION,
  CalibrationError,
  fitTopologyCostModel,
  parseCalibrationDataset,
  validateCalibrationDataset,
  type CalibratedCapability,
  type CalibrationApplicability,
  type CalibrationDataset,
  type CalibrationDatasetProvenance,
  type CalibrationEvidenceKind,
  type CalibrationFitDiagnostic,
  type CalibrationFitResult,
  type CalibrationModelConstants,
  type CalibrationObservation,
  type CalibrationQualityPolicy,
  type TransportCalibrationFitDiagnostic,
  type TransportCalibrationObservation,
} from "./calibration.js";
export {
  ALL_TO_ALL_TRAFFIC_SIGNATURE_PREFIX,
  COLLECTIVE_CALIBRATION_ALGORITHM,
  EXPERT_COLLECTIVE_CALIBRATION_ALGORITHM,
  DEFAULT_TOPOLOGY_COST_MODEL,
  TRANSFER_CALIBRATION_ALGORITHM,
  TOPOLOGY_COST_MODEL_REVISION,
  TopologyWorkloadError,
  assertCanonicalAllToAllTrafficSignature,
  canonicalAllToAllTrafficSignature,
  compareTopologyWorkloads,
  compileTopologyExpertLoadPlan,
  compileTopologyWorkloadPlan,
  resolveTopologyExpertOwnerPlacement,
  simulateTopologyWorkload,
  targetOnlyTopologyProfile,
  topologyProfileFromExpertCache,
  topologyProfileFromPipeline,
  topologyProfileFromSpeculative,
  type DeviceCapabilityCost,
  type TopologyComparisonEntry,
  type TopologyBackgroundPrefetch,
  type TopologyExpertLoad,
  type TopologyExpertLoadPlan,
  type TopologyExpertPlacement,
  type TopologyRoutedExpert,
  type TopologyCostModel,
  type TopologyComputeCapability,
  type CalibratedWorkItemRange,
  type TopologyResourceUtilization,
  type TransportCalibrationCurve,
  type TransportCalibrationPoint,
  type TransportOperationKind,
  type TopologyWorkUnit,
  type TopologyWorkloadMetrics,
  type TopologyWorkloadProfile,
  type TopologyModelWork,
  type TopologyPipelineComponentWork,
  type TopologyPipelineEdgeWork,
  type TopologyPipelinePhase,
  type TopologyPipelineWork,
  type TopologyWorkloadResult,
} from "./topology-workload.js";
